-- DDL (Data Definition Language) ★★★★★★
-- 테이블과 같은 데이터 구조를 정의하는데 사용되는 언어로, 생성, 변경, 삭제, 이름 변경 등 데이터 구조와 관련된 명령어들을 말한다.
-- 데이터 구조 생성, 수정, 삭제는 ROLLBACK 이 불가! ★★★

-- 1. 테이블 생성
CREATE TABLE EMP01 (
EMPNO     NUMBER(2),
ENAME     VARCHAR(50),
HEIGHT    NUMBER(5,2),
ADDRESS VARCHAR(200),
PHONE    VARCHAR(20)
);
DESC EMP;
DESC EMP01;
SELECT * FROM EMP01;
-- 전체 컬럼 복사
CREATE TABLE EMP02 AS SELECT * FROM EMP;
DESC EMP02;
SELECT * FROM EMP02;
-- 특정 컬럼 복사
CREATE TABLE EMP03 AS SELECT EMPNO, ENAME FROM EMP;
DESC EMP03;
SELECT * FROM EMP03;
-- 특정 행(DATA)만 복사
CREATE TABLE EMP04 AS SELECT * FROM EMP WHERE DEPTNO=10;
DESC EMP04;
SELECT * FROM EMP04;
-- 컬럼(데이터는 제외!)만 복사 조건 틀린값 
CREATE TABLE EMP05 AS SELECT * FROM EMP WHERE 1=0;
DESC EMP05;
SELECT * FROM EMP05;
CREATE TABLE EMP06 AS SELECT EMPNO, ENAME, SAL FROM EMP;
DESC EMP06;
SELECT * FROM EMP06;


-- 2. 테이블 수정
-- 컬럼추가 (맨 마지막 컬럼에 추가, 원하는 위치 X, 행에는 NULL 값 추가 > 설계 중요★)
-- ADD() < ()없어도 가능, 띄어쓰기 가능.
ALTER TABLE EMP01 ADD (JOB VARCHAR2(9));
DESC EMP01;
SELECT * FROM EMP01;
-- 컬럼 수정
ALTER TABLE EMP01 MODIFY (JOB VARCHAR2(30));
DESC EMP01;
-- 컬럼 삭제 ★★★
ALTER TABLE EMP01 DROP COLUMN JOB;
DESC EMP01;
-- UNUSED (미사용 상태) ★★★
ALTER TABLE EMP03 SET UNUSED (EMPNO);
SELECT * FROM EMP03;


-- 3. 테이블 삭제
DROP TABLE EMP01;
-- TRUNCATE : 테이블 내 데이터 전체 초기화 (복구 불가)
TRUNCATE TABLE EMP06;
SELECT * FROM EMP06;
-- RENAME : 테이블 이름 변경
RENAME EMP06 TO TEST;


-- 4. 데이터 딕셔너리 (Data Dictionary)
-- 접두어 USER/ALL/DBA 에 따라서 접근
SELECT * FROM TAB;
DESC USER_TABLES;
DESC ALL_TABLES;
DESC DBA_TABLES;
-- 현재 사용자 조회
SHOW USER;
-- 유저가 만든 테이블 이름을 출력
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME DESC;
DESC ALL_TABLES;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES WHERE OWNER='SCOTT';
SELECT OWNER, TABLE_NAME FROM DBA_TABLES;


-- 문제
-- 테이블 생성
CREATE TABLE DEPT_MISSION (
DNO NUMBER(2),
DNAME VARCHAR2(14),
LOC VARCHAR2(13)
);
CREATE TABLE EMP_MISSION (
ENO NUMBER(4),
ENAME VARCHAR2(10),
DNO NUMBER(2)
);
-- 컬럼 데이터 타입 변경
ALTER TABLE EMP_MISSION MODIFY (ENAME VARCHAR2(25));
-- 테이블 삭제
DROP TABLE EMP_MISSION;
-- 컬럼 삭제
ALTER TABLE DEPT_MISSION DROP COLUMN DNAME;
-- UNUSED (미사용 상태)
ALTER TABLE DEPT_MISSION SET UNUSED (LOC);
-- UNUSED 컬럼 제거 (미사용으로 표시된 컬럼을 드롭)
ALTER TABLE DEPT_MISSION DROP UNUSED COLUMNS;

COMMIT;


