-- 인덱스
-- 인덱스 개념
-- SQL 명령문의 처리 속도를 향상시키기 위해서 컬럼에 대해서 생성하는 오라클 객체
-- USER_IND_COLUMNS 데이터 딕셔너리 뷰
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME IN('EMP', 'DEPT');
DROP TABLE emp01;
CREATE TABLE emp01 AS SELECT * FROM emp;

-- 데이터 자가복제 (연습용)
INSERT INTO EMP01 SELECT * FROM EMP01;
SELECT * FROM EMP01;

-- 검색용 데이터 삽입
INSERT INTO EMP01(EMPNO, ENAME) VALUES(1111,'홍길동');
SET TIMING ON
SELECT DISTINCT EMPNO, ENAME FROM EMP01 WHERE ENAME = '홍길동';

-- 인덱스 생성
CREATE INDEX IDX_EMP01_ENAME ON EMP01(ENAME); -- 특정 컬럼에 인덱스 부여 한다
SELECT DISTINCT EMPNO, ENAME FROM EMP01 WHERE ENAME = '홍길동';

-- 인덱스 제거
-- DROP INDEX 인덱스명;



